force-app/main/default/objects/Registration_Form__c/Registration_Form__c.object-meta.xml
<CustomObject>
    <description>Registration form which a student will fill to confirm if will assist to the event.</description>
    <label>Registration Form</label>
    <nameField>
        <label>Registration Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registration Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Form__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Event which the student have registered for.</description>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Registration Forms</relationshipLabel>
    <relationshipName>Registration_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Form__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <description>Status of the registration.</description>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not resolved yet</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Form__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Student which have submitted the registration form.</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registration Forms</relationshipLabel>
    <relationshipName>Registration_Forms</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RegistrationFormController.cls
public with sharing class RegistrationFormController {

    @AuraEnabled
    public static void createRegistration(String firstName, String lastName, String email, String campaignId) {

        Contact newContact = new Contact(
            FirstName = firstName,
            LastName = lastName,
            Email = email
        );
        insert newContact;

       
        Registration_Form__c regForm = new Registration_Form__c(
            Event__c = campaignId, 
            Registration_Status__c = 'Accepted',   
            Student__c = newContact.Id
        );
        
        insert regForm;
    }
}